#!/bin/bash
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions

cleanCase
rm -rf constant/polyMesh constant/extendedFeatureEdgeMesh
rm -f constant/triSurface/*.eMesh
rm -f log.*
rm -rf postProcessing
[ -d 0.orig ] && rm -rf 0 && cp -r 0.orig 0
