#!/bin/bash
set -e
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions

runApplication surfaceFeatureExtract
runApplication blockMesh
runApplication snappyHexMesh -overwrite -noFunctionObjects
runApplication checkMesh -allGeometry -allTopology -noFunctionObjects
runApplication renumberMesh -overwrite -noFunctionObjects
runApplication potentialFoam -noFunctionObjects || true
runApplication simpleFoam || true

echo "Done."
